apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: spring-flux-demo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/JISH-65/spring-flux-demo
  branch: main
